apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: sadaiyer-gitops-yaml
    run: nginx-pod
  name: nginx-svc
  namespace: development
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/instance: sadaiyer-gitops-yaml
    run: nginx-pod
  type: NodePort
status:
  loadBalancer: {}
